package com.chirawn.app

import androidx.activity.compose.BackHandler
import androidx.compose.animation.AnimatedContent
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.chirawn.app.data.*
import com.chirawn.app.game.*
import kotlinx.coroutines.launch
import java.util.Calendar

private enum class Route { HOME, GAMES, PROFILE, SUDOKU, TWO048, SLIDING }
@Composable fun ChirawnApp(repo: HubRepository) {
 var route by rememberSaveable { mutableStateOf(Route.HOME) }; val stack = remember { mutableStateListOf<Route>() }
 fun go(r:Route) { stack.add(route);route=r }; BackHandler(enabled=stack.isNotEmpty()) { route=stack.removeLast() }
 AnimatedContent(route, label="route") { r -> when(r) { Route.HOME -> Home(repo,{go(Route.GAMES)},{go(Route.PROFILE)}); Route.GAMES -> GameCenter(repo,{go(Route.SUDOKU)},{go(Route.TWO048)},{go(Route.SLIDING)}); Route.PROFILE -> Profile(repo); Route.SUDOKU -> SudokuScreen(repo); Route.TWO048 -> Two048Screen(repo); Route.SLIDING -> SlidingScreen(repo) } }
}
@Composable private fun Shell(title:String, content:@Composable ColumnScope.()->Unit) = Scaffold(topBar={ CenterAlignedTopAppBar(title={Text(title,fontWeight=FontWeight.Bold)}) }) { p -> Column(Modifier.padding(p).padding(horizontal=20.dp).fillMaxSize(), content=content) }
@Composable private fun Home(repo:HubRepository, games:()->Unit, profile:()->Unit) { val p by repo.profile.collectAsStateWithLifecycle(null); val total by repo.total.collectAsStateWithLifecycle(0); val recent by repo.recent.collectAsStateWithLifecycle(emptyList()); val greeting=when(Calendar.getInstance().get(Calendar.HOUR_OF_DAY)){in 5..11->"Chào buổi sáng";in 12..17->"Chào buổi chiều";else->"Chào buổi tối"}; Shell("Chirawn") { Spacer(Modifier.height(12.dp)); Text(greeting,style=MaterialTheme.typography.titleLarge); Text(p?.nickname?:"Bạn",style=MaterialTheme.typography.displaySmall,fontWeight=FontWeight.Bold); Spacer(Modifier.height(24.dp)); ElevatedCard(Modifier.fillMaxWidth().clickable(games), colors=CardDefaults.elevatedCardColors(containerColor=MaterialTheme.colorScheme.primaryContainer)) { Row(Modifier.padding(22.dp),verticalAlignment=Alignment.CenterVertically) { Icon(Icons.Default.SportsEsports,null,Modifier.size(42.dp));Spacer(Modifier.width(16.dp));Column(Modifier.weight(1f)){Text("Game Center",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text("Ba trò chơi, một không gian riêng tư")};Icon(Icons.Default.ArrowForward,null) } }; Spacer(Modifier.height(18.dp)); Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){Stat("Đã chơi",total.toString(),Modifier.weight(1f));Stat("Chuỗi hiện tại","—",Modifier.weight(1f))}; Spacer(Modifier.height(22.dp));Text("Hoạt động gần đây",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold); if(recent.isEmpty()) Text("Chưa có ván nào. Hãy bắt đầu một trò chơi.",Modifier.padding(top=10.dp),color=MaterialTheme.colorScheme.onSurfaceVariant) else LazyColumn { items(recent){s->Text("${s.gameType.name.replace('_',' ')} · ${if(s.completed) "hoàn thành" else "đã dừng"}",Modifier.padding(vertical=9.dp))} }; Spacer(Modifier.weight(1f)); OutlinedButton(profile,Modifier.fillMaxWidth().padding(bottom=18.dp)){Icon(Icons.Default.Person,null);Spacer(Modifier.width(8.dp));Text("Hồ sơ của bạn")} } }
@Composable private fun Stat(label:String,value:String,modifier:Modifier){ Surface(modifier,shape=RoundedCornerShape(20.dp),color=MaterialTheme.colorScheme.secondaryContainer){Column(Modifier.padding(18.dp)){Text(value,style=MaterialTheme.typography.headlineMedium,fontWeight=FontWeight.Bold);Text(label,color=MaterialTheme.colorScheme.onSecondaryContainer)}} }
@Composable private fun GameCenter(repo:HubRepository,sudoku:()->Unit,two:()->Unit,sliding:()->Unit){val bests by repo.bests.collectAsStateWithLifecycle(emptyList());fun b(t:GameType)=bests.firstOrNull{it.gameType==t};Shell("Game Center"){Spacer(Modifier.height(12.dp));Text("Chọn một khoảng nghỉ nhỏ",style=MaterialTheme.typography.titleLarge);Spacer(Modifier.height(18.dp));GameCard("Sudoku","Lắng lại với những con số.",b(GameType.SUDOKU)?.bestTimeSeconds?.let{"Tốt nhất ${it}s"},sudoku);GameCard("2048","Ghép ô, giữ nhịp và đi xa hơn.",b(GameType.GAME_2048)?.bestScore?.takeIf{it>0}?.let{"Điểm cao $it"},two);GameCard("Sliding Puzzle","Sắp xếp từng bước thật gọn gàng.",b(GameType.SLIDING)?.bestTimeSeconds?.let{"Tốt nhất ${it}s"},sliding)}}
@Composable private fun GameCard(name:String,desc:String,best:String?,play:()->Unit){ElevatedCard(Modifier.fillMaxWidth().padding(bottom=14.dp)){Column(Modifier.padding(19.dp)){Text(name,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);Text(desc,color=MaterialTheme.colorScheme.onSurfaceVariant);if(best!=null)Text(best,Modifier.padding(top=8.dp),color=MaterialTheme.colorScheme.primary);Button(play,Modifier.align(Alignment.End).padding(top=10.dp)){Text("Chơi")}}}}
@Composable private fun Profile(repo:HubRepository){val p by repo.profile.collectAsStateWithLifecycle(null);val total by repo.total.collectAsStateWithLifecycle(0);val scope=rememberCoroutineScope();var name by remember(p){mutableStateOf(p?.nickname?:"Bạn")};Shell("Hồ sơ"){Spacer(Modifier.height(20.dp));Box(Modifier.size(84.dp).clip(RoundedCornerShape(42.dp)).background(MaterialTheme.colorScheme.primaryContainer),contentAlignment=Alignment.Center){Icon(Icons.Default.Person,null,Modifier.size(44.dp))};Spacer(Modifier.height(18.dp));OutlinedTextField(name,{name=it},label={Text("Biệt danh")},singleLine=true,modifier=Modifier.fillMaxWidth());Button({scope.launch{repo.nickname(name)}},Modifier.padding(top=10.dp)){Text("Lưu")};Spacer(Modifier.height(26.dp));Stat("Tổng số ván",total.toString(),Modifier.fillMaxWidth());Spacer(Modifier.height(12.dp));Text("Tổng thời gian chơi —",style=MaterialTheme.typography.bodyLarge);Text("Thành tựu hay nhất —",style=MaterialTheme.typography.bodyLarge,modifier=Modifier.padding(top=10.dp))}}

@Composable private fun GameHeader(score:String,time:Long,action:()->Unit){Row(Modifier.fillMaxWidth(),verticalAlignment=Alignment.CenterVertically){Text(score,style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold,modifier=Modifier.weight(1f));Text("${time/60}:${(time%60).toString().padStart(2,'0')}");IconButton(action){Icon(Icons.Default.Refresh,null)}}}
@Composable private fun SudokuScreen(repo:HubRepository){val vm=remember{SudokuViewModel(repo)};Shell("Sudoku"){GameHeader("Lỗi: ${vm.mistakes}",vm.seconds){vm.newGame()};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("Easy","Medium","Hard").forEach{d->FilterChip(d==vm.difficulty,{vm.newGame(d)},{Text(d)},Modifier.weight(1f))}};Spacer(Modifier.height(14.dp));Column(Modifier.fillMaxWidth().aspectRatio(1f).clip(RoundedCornerShape(12.dp)).background(MaterialTheme.colorScheme.surfaceVariant)){(0..8).forEach{r->Row(Modifier.weight(1f)){(0..8).forEach{c->val i=r*9+c;val sel=vm.selected==i;Box(Modifier.weight(1f).fillMaxHeight().padding(1.dp).background(if(sel) MaterialTheme.colorScheme.primaryContainer else Color.Transparent).clickable{vm.select(i)},contentAlignment=Alignment.Center){Text(if(vm.board[i]==0)"" else vm.board[i].toString(),fontWeight=if(vm.fixed[i])FontWeight.Bold else FontWeight.Normal)}}}};Spacer(Modifier.height(16.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceEvenly){(1..9).forEach{n->FilledTonalButton({vm.input(n)},contentPadding=PaddingValues(0.dp),modifier=Modifier.size(35.dp)){Text("$n")}}};TextButton({vm.input(0)},Modifier.align(Alignment.CenterHorizontally)){Text("Xóa ô")};if(vm.finished)Text("Hoàn thành!",Modifier.align(Alignment.CenterHorizontally),color=MaterialTheme.colorScheme.primary,fontWeight=FontWeight.Bold)}}
@Composable private fun Two048Screen(repo:HubRepository){val vm=remember{Game2048ViewModel(repo)};Shell("2048"){GameHeader("Điểm: ${vm.score}",vm.seconds){vm.restart()};Text(if(vm.over)"Kết thúc — chạm làm mới để chơi lại" else if(vm.won)"Bạn đã đạt 2048!" else "Vuốt để di chuyển",color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(18.dp));var drag by remember { mutableStateOf(androidx.compose.ui.geometry.Offset.Zero) };Column(Modifier.fillMaxWidth().aspectRatio(1f).clip(RoundedCornerShape(18.dp)).background(Color(0xFFB7AFA6)).pointerInput(Unit){detectDragGestures(onDragStart={drag=androidx.compose.ui.geometry.Offset.Zero},onDragEnd={if(kotlin.math.abs(drag.x)>kotlin.math.abs(drag.y))vm.move(if(drag.x>0)3 else 2) else if(drag.y!=0f)vm.move(if(drag.y>0)1 else 0)}) { _, amount -> drag+=amount }}){(0..3).forEach{r->Row(Modifier.weight(1f)){(0..3).forEach{c->val v=vm.cells[r*4+c];Box(Modifier.weight(1f).fillMaxHeight().padding(4.dp).clip(RoundedCornerShape(10.dp)).background(tileColor(v)),contentAlignment=Alignment.Center){Text(if(v==0)"" else "$v",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold,color=if(v>=8)Color.White else Color(0xFF403A35))}}}};Spacer(Modifier.height(22.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceEvenly){Button({vm.move(0)}){Text("↑")};Button({vm.move(2)}){Text("←")};Button({vm.move(1)}){Text("↓")};Button({vm.move(3)}){Text("→")}}}}
private fun tileColor(v:Int)=when(v){0->Color(0xFFD6D0C8);2->Color(0xFFEEE4DA);4->Color(0xFFEDE0C8);8->Color(0xFFF2B179);16->Color(0xFFF59563);32->Color(0xFFF67C5F);64->Color(0xFFF65E3B);else->Color(0xFF8F7A66)}
@Composable private fun SlidingScreen(repo:HubRepository){val vm=remember{SlidingViewModel(repo)};Shell("Sliding Puzzle"){GameHeader("Nước đi: ${vm.moves}",vm.seconds){vm.restart()};Text("Sắp xếp từ 1 đến 8",color=MaterialTheme.colorScheme.onSurfaceVariant);Spacer(Modifier.height(20.dp));Column(Modifier.fillMaxWidth().aspectRatio(1f).clip(RoundedCornerShape(18.dp)).background(MaterialTheme.colorScheme.secondaryContainer)){(0..2).forEach{r->Row(Modifier.weight(1f)){(0..2).forEach{c->val i=r*3+c;val v=vm.tiles[i];Box(Modifier.weight(1f).fillMaxHeight().padding(5.dp).clip(RoundedCornerShape(15.dp)).background(if(v==0)Color.Transparent else MaterialTheme.colorScheme.primary).clickable(enabled=v!=0){vm.tap(i)},contentAlignment=Alignment.Center){Text(if(v==0)"" else "$v",style=MaterialTheme.typography.headlineMedium,color=Color.White,fontWeight=FontWeight.Bold)}}}};if(vm.finished)Text("Hoàn thành!",Modifier.align(Alignment.CenterHorizontally),color=MaterialTheme.colorScheme.primary,fontWeight=FontWeight.Bold)}}
